---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

resources:
  requests:
    cpu: 1000
    memory: 2GiB

steps:
- name: deploy_ui
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/lev-ci
  commands:
  - echo "$${DOCKER_PASSWORD}" | docker login -u "ukhomeofficedigital+lev" --password-stdin "quay.io"
  - npm install -g pnpm
  - cd 'apps/ui'
  - make deploy kubectl="kubectl --insecure-skip-tls-verify --server=$${KUBE_SERVER} --namespace=$${KUBE_NAMESPACE} --token=$${KUBE_TOKEN}"
  environment:
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    KUBE_CONTAINER_UI:
      from_secret: KUBE_CONTAINER_UI
    KUBE_DEPLOYMENT_UI:
      from_secret: KUBE_DEPLOYMENT_UI
    KUBE_NAMESPACE:
      from_secret: KUBE_NAMESPACE
    KUBE_SERVER:
      from_secret: KUBE_SERVER
    KUBE_TOKEN:
      from_secret: KUBE_TOKEN
  when:
    branch:
    - master
    event:
    - push
  resources:
    limits:
      cpu: 1000
      memory: 2GiB

- name: notify_slack_success
  pull: if-not-exists
  image: plugins/slack:1.0
  settings:
    channel: general
    template: "*Deployed {{repo.name}} to Dev* - <{{build.link}}|#{{build.number}}>\n"
    username: Drone
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    branch:
    - master
    event:
    - push
    status:
    - success

- name: notify_slack_failure
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: alerts
    template: "*Failed to deploy {{repo.name}} to Dev*\nAuthor: {{build.author}}\nDuration: {{since job.started}} Job: <{{build.link}}|#{{build.number}}>\nCommit: {{build.commit}}\n"
    username: Drone
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    branch:
    - master
    event:
    - push
    status:
    - failure

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
